### ISSUE TITLE
Asyncua Exception importing custom_components.asyncua

### ISSUE THREAD

**Issue by paolo-seveso** [KVSoong/asyncua#5]
I installed last version of asyncua on Home Assistant 2025.2.2 but when I check configuration (Developer tools -> Check configuration) I receive these warnings:
**Platform error ‘sensor’ from integration ‘asyncua’ - Exception importing custom_components.asyncua.sensor
Component error: asyncua - Exception importing custom_components.asyncua**

This is my configuration.yaml with asyncua section copy&past from help page:

```
# Loads default set of integrations. Do not remove.
default_config:

# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml

homeassistant:
  customize_glob:
    sensor.xiem*_eat*:
      last_reset: '1970-01-01T00:00:00+00:00'
      device_class: energy
      state_class: measurement
      
# Archiviazione dati a breve periodo su sqlite integrato in HA (home-assistant_v2.db)
recorder:
  purge_keep_days: 7
  include:
    domains:
      - alarm_control_panel
    entity_globs:
      - sensor.iem*
      - sensor.solaredge*

# Archiviazione sul lungo periodo con influxdb
influxdb:
  host: localhost
  port: 8086
  database: home_assistant
  username: homeassistant
  password: homeassistant
  ssl: false
  max_retries: 3
  default_measurement: state
  include:
    entity_globs:
      - sensor.iem*

asyncua:
  - name: "opcua-01" # Unique name to identify the server. Will be used by the sensors to indicate which server to get the node value.
    url: "opc.tcp://192.168.1.204:4840/" # URL of the server.
    scan_interval: 10 # Optional. Interval for coordinator to read from OPCUA. Default is set at 30s.
    # username: admin # Optional username
    # password: admin # Optional password

sensor:
  - platform: asyncua
    nodes:
      - name: opcua-01-sensor-01 # Name of the sensor
        unique_id: opcua-01-sensor-01 # Unique ID of the sensor
        device_class: temperature # Device class according to Homeassistant sensors
        hub: opcua-01 # OPCUA unique name defined in the coordinator that serve the data.
        nodeid: "ns=1;s=20096" # Node id from OPCUA server
        unit_of_measurement: °C # Optional unit of measurement.


modbus: !include modbus.yalm
knx: !include knx.yalm

template:
  - sensor:
      - name: iEM3155_EAT_2
        unique_id: hub13204eat_2
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.iem3155_eat') | int / 1000 }}"
        availability: "{{ states('sensor.iem3155_eat')|is_number }}"
      - name: iEM2050_EAT_kWh
        unique_id: hub13205eat_kwh
        unit_of_measurement: "kWh"
        device_class: energy
        state_class: total_increasing
        state: "{{ states('sensor.iem2050_eat') | int / 1000 }}"
        availability: "{{ states('sensor.iem2050_eat')|is_number }}"

logger:
  logs:
    homeassistant.components.modbus: debug
    pymodbus.client: debug

fan:
  - platform: template
    fans:
      preset_mode_fan:
        friendly_name: "Preset Mode Fan Example"
        value_template: "{{ states('fan.percentage_fan') }}"
        turn_on:
          - service: fan.turn_on
            target:
              entity_id: fan.percentage_fan
        turn_off:
          - service: fan.turn_off
            target:
              entity_id: fan.percentage_fan
        percentage_template: >
          {{ state_attr('fan.percentage_fan', 'percentage') }}
        speed_count: 3
        set_percentage:
          - service: fan.set_percentage
            target:
              entity_id: fan.percentage_fan
            data:
              percentage: "{{ percentage }}"
        preset_modes:
          - "off"
          - "low"
          - "medium"
          - "high"
        preset_mode_template: >
          {% if is_state('fan.percentage_fan', 'on') %}
            {% if state_attr('fan.percentage_fan', 'percentage') == 100  %}
              high
            {% elif state_attr('fan.percentage_fan', 'percentage') == 66 %}
              medium
            {% else %}
              low
            {% endif %}
          {% else %}
            off
          {% endif %}
        set_preset_mode:
          - service: fan.set_percentage
            target:
              entity_id: fan.percentage_fan
            data:
              percentage: >-
                {% if preset_mode == 'high' %}
                  100
                {% elif preset_mode == 'medium' %}
                  66
                {% elif preset_mode == 'low' %}
                  33
                {% else %}
                  0
                {% endif %}

```
Thanks for your support.
